FROM ubuntu:18.04

RUN apt-get update; \
    apt-get install -y \
        cmake \
        vim \
        git \
        wget \
        doxygen \
        libpcre3 libpcre3-dev \
        gfortran \
        libssl-dev \
        python-pip \
        python-dev \
        libboost-all-dev \
        swig; \
    pip install numpy 

# get frensie
WORKDIR /root
COPY ./ /root/FRENSIE/
RUN mkdir FRENSIE_bld
WORKDIR /root/FRENSIE_bld
RUN cmake -D CMAKE_BUILD_TYPE:STRING=RELEASE -D CMAKE_TIMING_VERBOSE:BOOL=ON ../FRENSIE
RUN make -j 8 > log
